Component/link
ownego/polaris-vue pull request #220
Opened 2023-12-13 10:13 UTC by HQCuong

2023-12-19 02:30 UTC, juzser requested changes

2023-12-19 02:30 UTC, juzser commented on src/components/Link/type.ts
> +/**
Filename should be `types.ts`

2023-12-22 07:18 UTC, haild173094 commented on docs/components/Link/README.md
> +
Check more info in link.mdx file

2023-12-22 09:12 UTC, juzser requested changes

2023-12-22 09:12 UTC, juzser commented on src/components/Link/Link.vue
> +./types
.

2023-12-22 09:12 UTC, juzser commented on src/components/Link/types.ts
> +    /**
tab = 4 spaces?

2023-12-28 02:17 UTC, juzser requested changes

2023-12-28 02:17 UTC, juzser commented on docs/components/Link/README.md
> +## Best practices
Wrap additional contents inside `<div font-size...` element to reduce font size

2023-12-28 10:43 UTC, haild173094 approved these changes

2023-12-29 02:35 UTC, juzser approved these changes

2023-12-29 03:34 UTC, merged