UPdate: docs for Card preview
ownego/polaris-vue pull request #230
Opened 2023-12-19 03:58 UTC by haild173094

2023-12-19 05:20 UTC, juzser requested changes

2023-12-19 05:20 UTC, juzser commented on src/components/Card/Card.vue
> +watch(
.

2023-12-19 05:20 UTC, juzser commented on src/components/Card/types.ts
> +  background?: ColorBackgroundAlias;
Is it missing comment?

2023-12-19 05:20 UTC, juzser commented on src/components/Card/types.ts
> +  background?: ColorBackgroundAlias;
![Uploading Screenshot 2023-12-19 at 12.16.46.png…]()

2023-12-21 10:15 UTC, HQCuong commented on src/components/ShadowBevel/types.ts
> +import type {ResponsiveProp} from '@/utilities/css';
missing space

2023-12-21 10:15 UTC, HQCuong commented on src/components/Card/Card.vue
> +  :box-shadow="'100'",
box-shadow="100"

2023-12-21 10:17 UTC, HQCuong commented on src/components/ShadowBevel/ShadowBevel.vue
> +import {getResponsiveValue} from '@/utilities/css';
missing space

2023-12-21 10:17 UTC, HQCuong commented on src/components/ShadowBevel/ShadowBevel.vue
> +import type {ResponsiveProp} from '@/utilities/css';
.

2023-12-21 10:17 UTC, HQCuong commented on src/components/Card/Card.vue
> +import type {
optional: don't need to break line here

2023-12-21 10:18 UTC, HQCuong commented on src/components/Card/Card.vue
> +const defaultBorderRadius: BorderRadiusAliasOrScale = '300';
breakline

2023-12-21 10:20 UTC, HQCuong requested changes
convention

2023-12-22 09:17 UTC, juzser requested changes

2023-12-22 09:17 UTC, juzser commented on docs/components/Card/AllElement.vue
> +
.

2023-12-22 09:17 UTC, juzser commented on docs/components/Card/SectionAndAction.vue
> +          onClick={() => {}}
.

2023-12-22 09:17 UTC, juzser commented on docs/components/Card/SectionAndCriticalAction.vue
> +            @Click="() => {}"
.

2023-12-22 09:17 UTC, juzser commented on docs/components/Card/SectionAndCriticalAction.vue
> +            @Click="() => {}"
.

2023-12-22 09:17 UTC, juzser commented on docs/components/Card/WithMultipleFooterAction.vue
> +            <Button disclosure accessibilityLabel="More" @Click="handleToggleAction">
. Click

2023-12-22 09:17 UTC, juzser commented on docs/components/Card/WithSeparateHeader.vue
> +          active={actionActive}
.

2023-12-22 09:17 UTC, juzser commented on docs/components/Card/WithSeparateHeader.vue
> +          activator={disclosureButtonActivator}
.

2023-12-23 14:42 UTC, juzser commented on docs/components/Card/SectionAndAction.vue
> +          onClick={() => {}}
`@click="..."`

2023-12-23 15:03 UTC, juzser approved these changes

2023-12-23 15:03 UTC, merged