Component/ BlockStack
ownego/polaris-vue pull request #231
Opened 2023-12-21 07:12 UTC by haild173094

2023-12-21 10:21 UTC, HQCuong commented on src/components/BlockStack/BlockStack.vue
> +<script setup lang="ts">
missing define slots

2023-12-21 10:22 UTC, HQCuong commented on src/components/BlockStack/types.ts
> +import type {
convention

2023-12-21 10:25 UTC, HQCuong requested changes
missing define slots, convention

2023-12-22 09:10 UTC, juzser requested changes

2023-12-22 09:10 UTC, juzser commented on src/components/BlockStack/BlockStack.vue
> +const style: any = {
Should be `computed`

2023-12-25 02:43 UTC, juzser approved these changes

2023-12-25 02:43 UTC, juzser commented on docs/components/BlockStack/PreviewPlaceholder.vue
> +const wrapperStyle = {
computed

2023-12-25 02:49 UTC, merged