component/Select
ownego/polaris-vue pull request #273
Opened 2024-01-13 07:48 UTC by juzser

2024-01-15 04:42 UTC, HQCuong requested changes

2024-01-15 04:42 UTC, HQCuong commented on src/components/Select/Select.vue
> +const uniqId = getCurrentInstance()?.uid;
You can use useId.ts `use/useId.ts`

2024-01-16 04:11 UTC, HQCuong commented on src/components/Select/Select.vue
> +import { computed, getCurrentInstance } from 'vue';
remove unuse import

2024-01-16 04:42 UTC, haild173094 approved these changes

2024-01-16 08:59 UTC, merged