Component/KeyboardKey
ownego/polaris-vue pull request #284
Opened 2024-01-17 04:29 UTC by miph1309

2024-01-17 07:12 UTC, juzser requested changes

2024-01-17 07:12 UTC, juzser commented on src/components/KeyboardKey/KeyboardKey.vue
> +</script>
Missing end line

2024-01-17 07:12 UTC, juzser commented on docs/components/KeyboardKey/README.md
> +## Best practices
Missing div font size

2024-01-17 07:59 UTC, juzser requested changes

2024-01-17 07:59 UTC, juzser commented on docs/components/KeyboardKey/Default.vue
> +</script>
Remove these lines

2024-01-17 10:09 UTC, haild173094 approved these changes

2024-01-19 02:35 UTC, juzser approved these changes

2024-01-19 02:36 UTC, merged