Component/popover
ownego/polaris-vue pull request #300
Opened 2024-01-24 16:26 UTC by HQCuong

2024-01-25 02:21 UTC, haild173094 requested changes

2024-01-25 02:21 UTC, haild173094 commented on docs/components/Popover/README.md
> +- To put a list of actions in a popover, [use the action list component](https://polaris.shopify.com/components/ActionList)
path to docs (`/components/ActionList`)

2024-01-25 02:21 UTC, haild173094 commented on docs/components/Popover/README.md
> +- To let merchants select simple options from a list, [use the select component](https://polaris.shopify.com/components/Select)
.

2024-01-25 02:21 UTC, haild173094 commented on docs/components/Popover/README.md
> +Popovers usually contain an [option list](https://polaris.shopify.com/components/OptionList) or an [action list](https://polaris.shopify.com/components/ActionList), but can also contain other control
.

2024-01-25 02:21 UTC, haild173094 commented on docs/components/Popover/README.md
> +To assist screen readers with sending focus to an [action list](https://polaris.shopify.com/components/ActionList), pass `autofocusTarget='first-node'` to `Popover`. This will avoid known issues a sc
.

2024-01-25 02:21 UTC, haild173094 commented on docs/components/Popover/README.md
> +
Will need Events :thinking:

2024-01-25 02:21 UTC, haild173094 commented on src/components/Popover/components/PopoverOverlay/popoverOverlayClass.ts
> +return classNames(
tab

2024-01-25 02:46 UTC, juzser requested changes

2024-01-25 02:46 UTC, juzser commented on docs/components/Popover/README.md
> +- To put a list of actions in a popover, [use the action list component](https://polaris.shopify.com/components/ActionList)
Link to our component.
This line and those below.

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/Popover.vue
> +      v-bind="{ ...props }",
`v-bind="props"`

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/components/Pane/Pane.vue
> +type Slots = {
Should change the name to `PaneSlots`, to avoid duplication on running type generate.

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/components/Pane/Pane.vue
> +type Emits = {
.

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/components/PopoverOverlay/PopoverOverlay.vue
> +    v-bind="{ ...overlay.props }",
.

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/components/PopoverOverlay/popoverOverlayClass.ts
> +return classNames(
Tab indent?

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/components/PopoverOverlay/popoverOverlayClass.ts
> +import { computed } from 'vue';
What's this file for?

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/components/PopoverOverlay/types.ts
> +import type { PositionedOverlayProps } from "@/components/PositionedOverlay/PositionedOverlay.vue";
Single quote `'`

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/components/PopoverOverlay/types.ts
> +import type { PositionedOverlayProps } from "@/components/PositionedOverlay/PositionedOverlay.vue";
This file is duplicated with `Popover/types.ts` ?

2024-01-25 02:46 UTC, juzser commented on src/components/Popover/types.ts
> +import type { PositionedOverlayProps } from '@/components/PositionedOverlay/PositionedOverlay.vue';
Duplicate file?

2024-01-25 02:46 UTC, juzser commented on src/components/PositionedOverlay/PositionedOverlay.vue
> +type Emits = {
.

2024-01-25 02:46 UTC, juzser commented on src/components/PositionedOverlay/PositionedOverlay.vue
> +  scrollOut: [];
`scroll-out`

2024-01-25 02:46 UTC, juzser commented on src/components/Scrollable/Scrollable.vue
> +  v-bind="{ ...scrollable.props }",
.

2024-01-25 02:46 UTC, juzser commented on src/utilities/component.ts
> +import { type Component, h } from 'vue';
`h`?

2024-01-25 02:46 UTC, juzser commented on src/utilities/math.ts
> +import {Rect} from '../../../utilities/geometry';
use alias path

2024-01-25 02:46 UTC, juzser commented on src/utilities/types.ts
> +export enum Key {
:-? I guess it's already existed in this file

2024-01-26 02:45 UTC, haild173094 approved these changes

2024-01-26 04:46 UTC, juzser approved these changes

2024-01-26 05:07 UTC, merged