Component/Banner (wait for Legacy, TextContainer, Modal)
ownego/polaris-vue pull request #303
Opened 2024-01-29 07:51 UTC by miph1309

2024-02-20 05:02 UTC, juzser requested changes

2024-02-21 03:54 UTC, haild173094 approved these changes

2024-02-21 07:49 UTC, juzser requested changes

2024-02-21 07:49 UTC, juzser commented on src/components/Banner/context.ts
> +  const context = inject<boolean>('false');
Mistake

2024-02-21 07:49 UTC, juzser commented on src/components/Banner/Banner.vue
> +const attrs = useAttrs();
Does this work?

2024-02-22 02:32 UTC, juzser approved these changes

2024-02-22 02:32 UTC, merged