Component/MediaCard (wait for legacy card)
ownego/polaris-vue pull request #304
Opened 2024-01-29 08:53 UTC by miph1309

2024-02-20 05:06 UTC, juzser requested changes

2024-02-20 05:06 UTC, juzser commented on src/components/MediaCard/MediaCard.vue
> +              v-if="typeof title === 'string'",
It's not correct, it should be `v-if="hasSlot(slots.title)"` => display slot
else, using title prop. 
Check other components for more information

2024-02-20 05:06 UTC, juzser commented on src/components/MediaCard/MediaCard.vue
> +const actionClassName = classNames(
computed

2024-02-22 02:40 UTC, haild173094 requested changes

2024-02-22 02:40 UTC, haild173094 commented on src/components/MediaCard/MediaCard.vue
> +                  @click="attrs['onDismiss']",
should it be `@click="emits('dismiss')"` :thinking:

2024-02-22 02:40 UTC, haild173094 commented on src/components/MediaCard/MediaCard.vue
> +                  preferredAlignment="left"
`,`

2024-02-22 02:40 UTC, haild173094 commented on src/components/MediaCard/MediaCard.vue
> +                  preferredPosition="below"
`,`

2024-02-22 02:40 UTC, haild173094 commented on src/components/MediaCard/MediaCard.vue
> +              as="h2"
`,`

2024-02-22 03:47 UTC, juzser approved these changes

2024-02-22 03:47 UTC, merged